# Lambda Function for Authorizer
  AuthorizerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              # Example: Check for a specific token in the Authorization header
              token = event['authorizationToken']
              if token == 'allow':
                  return {
                      'principalId': 'user',
                      'policyDocument': {
                          'Version': '2012-10-17',
                          'Statement': [
                              {
                                  'Action': 'execute-api:Invoke',
                                  'Effect': 'Allow',
                                  'Resource': event['methodArn']
                              }
                          ]
                      }
                  }
              else:
                  return {
                      'principalId': 'user',
                      'policyDocument': {
                          'Version': '2012-10-17',
                          'Statement': [
                              {
                                  'Action': 'execute-api:Invoke',
                                  'Effect': 'Deny',
                                  'Resource': event['methodArn']
                              }
                          ]
                      }
                  }
      Runtime: py
