MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NotificationsTable
      AttributeDefinitions:
        - AttributeName: NotificationId
          AttributeType: S
      KeySchema:
        - AttributeName: NotificationId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Resources:  
AccessLogBucket: 
Type: "AWS::S3::Bucket" 
Properties: 
AccessControl: LogDeliveryWrite 
 
MainBucket: 
Type: "AWS::S3::Bucket" 
Properties: 
BucketName: !Ref BucketName 
BucketEncryption: 
ServerSideEncryptionConfiguration: 
- ServerSideEncryptionByDefault: 
SSEAlgorithm: AES256 
LoggingConfiguration: 
DestinationBucketName: !Ref AccessLogBucket
