AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: vcs-dev-notification-api
      Description: API for managing audiences, notifications, and templates.

  RootResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      RestApiId: !Ref ApiGateway
      PathPart: v1

  AudiencesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref RootResource
      RestApiId: !Ref ApiGateway
      PathPart: audiences

  AudiencesAudienceNameResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref AudiencesResource
      RestApiId: !Ref ApiGateway
      PathPart: '{audience-name}'

  AudiencesGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref AudiencesAudienceNameResource
      RestApiId: !Ref ApiGateway
      RequestParameters:
        method.request.path.audience-name: true
      Integration:
        IntegrationHttpMethod: GET
        Type: MOCK

  NotificationsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref RootResource
      RestApiId: !Ref ApiGateway
      PathPart: notifications

  NotificationsPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref NotificationsResource
      RestApiId: !Ref ApiGateway
      Integration:
        IntegrationHttpMethod: POST
        Type: MOCK

  NotificationsReceiptIdResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref NotificationsResource
      RestApiId: !Ref ApiGateway
      PathPart: '{receiptId}'

  NotificationsReceiptIdStatusResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref NotificationsReceiptIdResource
      RestApiId: !Ref ApiGateway
      PathPart: status

  NotificationsReceiptIdStatusGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref NotificationsReceiptIdStatusResource
      RestApiId: !Ref ApiGateway
      RequestParameters:
        method.request.path.receiptId: true
      Integration:
        IntegrationHttpMethod: GET
        Type: MOCK

  TemplatesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref RootResource
      RestApiId: !Ref ApiGateway
      PathPart: templates

  TemplatesGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      ResourceId: !Ref TemplatesResource
      RestApiId: !Ref ApiGateway
      Integration:
        IntegrationHttpMethod: GET
        Type: MOCK

  TemplatesPostMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref TemplatesResource
      RestApiId: !Ref ApiGateway
      Integration:
        IntegrationHttpMethod: POST
        Type: MOCK

  TemplatesTemplateNameResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref TemplatesResource
      RestApiId: !Ref ApiGateway
      PathPart: '{template-name}'

  TemplatesTemplateNameDeleteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: DELETE
      ResourceId: !Ref TemplatesTemplateNameResource
      RestApiId: !Ref ApiGateway
      RequestParameters:
        method.request.path.template-name: true
      Integration:
        IntegrationHttpMethod: DELETE
        Type: MOCK

  TemplatesTemplateNamePutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: PUT
      ResourceId: !Ref TemplatesTemplateNameResource
      RestApiId: !Ref ApiGateway
      RequestParameters:
        method.request.path.template-name: true
      Integration:
        IntegrationHttpMethod: PUT
        Type: MOCK
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGateway
    DependsOn:
      - AudiencesGetMethod
      - NotificationsPostMethod
      - NotificationsReceiptIdStatusGetMethod
      - TemplatesGetMethod
      - TemplatesPostMethod
      - TemplatesTemplateNameDeleteMethod
      - TemplatesTemplateNamePutMethod
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Sub dev
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiGatewayDeployment

Outputs:
  ApiGatewayUrl:
    Description: Base URL of the API Gateway
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/v1
